name: Security Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Create advanced scanner script
      run: |
        cat << EOF > advanced_scanner.py
        # Paste the content of the advanced scanner script here
        EOF

    - name: Run security scan
      run: python advanced_scanner.py
      continue-on-error: true

    - name: Check for scan results
      id: check_results
      run: |
        if [ -f security-scan-results.txt ]; then
          echo "file_exists=true" >> $GITHUB_OUTPUT
          if grep -q "Detected Vulnerabilities:" security-scan-results.txt; then
            echo "vulnerabilities_found=true" >> $GITHUB_OUTPUT
          else
            echo "vulnerabilities_found=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "file_exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Upload scan results
      uses: actions/upload-artifact@v3
      with:
        name: security-scan-results
        path: security-scan-results.txt

    - name: Comment PR
      uses: actions/github-script@v6
      if: always()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const fs = require('fs')
          let comment = '## Security Scan Results\n\n'
          
          if ('${{ steps.check_results.outputs.file_exists }}' === 'true') {
            const scanResults = fs.readFileSync('security-scan-results.txt', 'utf8')
            comment += '```\n' + scanResults + '\n```\n\n'
            
            if ('${{ steps.check_results.outputs.vulnerabilities_found }}' === 'true') {
              comment += '⛔ **Vulnerabilities detected. Please address these issues before merging.**'
            } else {
              comment += '✅ **No vulnerabilities detected.**'
            }
          } else {
            comment += '⚠️ **Error: The security scan failed to complete. Please review the workflow logs for more information.**'
          }
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          })

    - name: Fail if vulnerabilities found or scan failed
      if: steps.check_results.outputs.vulnerabilities_found == 'true' || steps.check_results.outputs.file_exists == 'false'
      run: exit 1